stages:
  - build
  - release

build:
  stage: build
  image: golang
  script:
    - go get
    - go build -o padawan-linux-amd64 .
    - GOARCH=arm64 GOOS=darwin go build -o padawan-darwin-arm64 .
  artifacts:
    untracked: false
    expire_in: 10 minutes
    paths:
      - "padawan-linux-amd64"
      - "padawan-darwin-arm64"
  only:
    - main

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli
  dependencies:
    - build
  script:
    - export BUILD_JOB_ID=$(cat .build_id)
    - echo "Build release"
  release:
    tag_name: $CI_COMMIT_BRANCH-${CI_COMMIT_SHA:1:8}
    description: "New release of padawan client"
    name: "Padawan cli version $CI_COMMIT_BRANCH-${CI_COMMIT_SHA:1:8}"
    assets:
      links:
        - name: "padawan-linux-amd64"
          url: "https://gitlab.viarezo.fr/$CI_PROJECT_PATH/-/jobs/$CI_JOB_ID/artifacts/raw/padawan-linux-amd64"
        - name: "padawan-darwin-arm64"
          url: "https://gitlab.viarezo.fr/$CI_PROJECT_PATH/-/jobs/$CI_JOB_ID/artifacts/raw/padawan-darwin-arm64"
  artifacts:
    untracked: false
    expire_in: 30 days
    paths:
      - "padawan-linux-amd64"
      - "padawan-darwin-arm64"
  only:
    - main
